language: python
services:
- docker
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
after_success:
  - |
      if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+.* ]]; then
      make docker_deploy
      fi
      