language: python
services:
- docker
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
- make docker_build
after_success:
- |
  if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+.* ]]; then
  make docker_push
  fi
env:
  secure: KNKjf14v/PhpHr7M9Rht0+fj6nU98WHKDCxPF9C4MM6WZsR+TVe5vPSZE+RZOk2gm8vqr55p8DUawANYz6OW1hVNcURpw2gJt5iZKibgxnMAz3vGxe8trJ223ba2yGIhcbcfr70fOoeP/GkZUdgZMKkrnXtL/MoBRhuPwmLLEeTPEcBUINQrq/0RfAPTAC7n2EPABgWWE5dpNxQr9atOS2WmcrgNxp/zfa3oUvx7j8x0mppEScbAStAyUdcEV3Hh7SEQMZQNRVBfWE/ecCOQfsifPqGJ5IaKn8hON3ix9zysMCoFqUYmXSafAmcl5Rc7Oij2PXBb/5bCxwNzZZyFWdr/XIAHFBkXBYSvNf63vKlx4Auv7CwK6ACZFdEBM01qfjrZZpAJ0a4WTcq+bhMNhEckZl03vXEq+f+WRfSGeuPfKbahF6oKBt6EaswzkbU5ZQB/bxDpVpb5Ck4bD3+T++g/HPpdIK4udC/ARdbFcg8EeHQNAgR+2NHxZWy2xWjQ6pl9iYreZ2hMZ6U3x1ImZFFozOsb4NYWe3j2iX3MKkZhbr5yvjBXKtMtZg3fghEvV4HrPNaCOfb2IEzQSpJomr/xEUtTlGtCYe0oK4vF4nzndH06D5poUgseJouFw76xHy+E+6YD06iQzJLGl+5mk2+XMPx4ptuwXphLTGGtrUM=
deploy:
  provider: heroku
  app: blooming-tor-57861
  api_key: ${HEROKU_API_KEY}