language: python
services:
- docker
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
after_success:
  - |
      if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+.* ]]; then
        @docker login --username $(USERNAME) --password $${DOCKER_PASSWORD};
	      docker tag hello-world-printer ${TAG}:${TRAVIS_TAG};
	      docker push ${TAG}:${TRAVIS_TAG};
	      docker logout;
      fi
